images-list

This PR adds images for `jettech/kube-webhook-certgen` and `squareup/ghostunnel` and updates some of the currently mirrored images to their latest versions.
Related Issue: https://github.com/rancher/rancher/issues/28441

Add and update images for Monitoring / Alerting V2

---

images-list

Adding images used for security updates in v1 `rancher-monitoring` and `rancher-external-dns`
rancher-monitoring PR: https://github.com/rancher/system-charts/pull/334
rancher-external-dns PR: https://github.com/rancher/system-charts/pull/336

Add images for v1 rancher-monitoring and rancher-external-dns

---

images-list

Update logging images to match Banzai Logging Operator 3.7.0 helm chart
images. This includes four images: logging-operator, fluentd, fluentbit,
and fluentbit-debug.
version bump
Issue: [#29642](https://github.com/rancher/rancher/issues/29642)
n/a

Update logging images to match 3.7.0 upstream

---

images-list

These image updates are required for https://github.com/rancher/charts/pull/836.
New image tags for:
- curlimages/curl rancher/curlimages-curl 7.73.0
- grafana/grafana rancher/grafana-grafana 7.2.1
- jettech/kube-webhook-certgen rancher/jettech-kube-webhook-certgen v1.5.0
- jimmidyson/configmap-reload rancher/jimmidyson-configmap-reload v0.4.0
- kiwigrid/k8s-sidecar rancher/kiwigrid-k8s-sidecar 1.1.0
New images that require new repositories:
- grafana/grafana-image-renderer rancher/grafana-grafana-image-renderer 2.0.0
- Created a ticket to create the new repository
New images that have existing Rancher repositories but have been added to the scripts for the first time:
- quay.io/prometheus-operator/prometheus-config-reloader rancher/coreos-prometheus-config-reloader v0.43.0
- …

Update images for Monitoring rebase to 11.0.0

---

images-list

Update logging images to match 3.7.3 upstream. Fluentd and fluentbit
are the same versions as 3.7.0.
version bump
Relevant issue: https://github.com/rancher/rancher/issues/29642
n/a

Update logging images to match 3.7.3 upstream

---

images-list

Both repositories `quay.io/prometheus-operator/prometheus-config-reloader` and `quay.io/prometheus-operator/prometheus-operator` do not have a tag for `v0.39.0` since Prometheus Operator never migrated to using `quay.io/prometheus-operator/*` until release `v0.38.3` based on the [release notes](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.38.3). `v0.38.3` was released after `v0.39.0`.
We should be pulling images from the old repository at `quay.io/coreos/*` instead, which has both image tags:
- [`quay.io/coreos/prometheus-config-reloader:v0.39.0`](https://quay.io/repository/coreos/prometheus-config-reloader?tag=v0.39.0&tab=tags)
- [`quay.io/coreos/prometheus-operator:v0.39.0`](https://quay.io/repository/coreos/prometheus-operator?tag=v0.39.0&tab=tags)
- Note: …

Fix repos for Monitoring V1 upgrade to v0.39.0

---

images-list

Mirror new version directxman12/k8s-prometheus-adapter-amd64:v0.7.0
Version bump
https://github.com/rancher/charts/pull/844

Mirror new version directxman12/k8s-prometheus-adapter-amd64:v0.7.0

---

images-list

Version bump
Relevant issue: https://github.com/rancher/rancher/issues/29892
```bash
[nickgerace at rancherbook in ~/Developer/rancher-charts] (130) (dev-v2.5-source-logging-382)
% docker pull banzaicloud/logging-operator:3.8.2 
3.8.2: Pulling from banzaicloud/logging-operator
Status: Image is up to date for banzaicloud/logging-operator:3.8.2
docker.io/banzaicloud/logging-operator:3.8.2
```

Add logging operator 3.8.2 image

---

.github/PULL_REQUEST_TEMPLATE.md

PR Template Update
Additional manual checks need to be added to attempt a manual intervention for missing Rancher Dockerhub repos on new entires and overwriting existing Rancher Dockerhub images.

Add rancher dockerhub and not changing mirrored images check to list

---

images-list

Verison Bump
Kiali version from v1.28.0 to v1.29.0
https://github.com/rancher/rancher/issues/30470
Kiali v1.28.0 was already mirrored, but will not be used in upcoming releases.

Bump kiali version

---

images-list

Adding a new repository to support prometheus adapter ARM. Need to create repository first.
Related Issue: https://github.com/rancher/rancher/issues/29871

Add correct image for Prometheus Adapter

---

images-list

Version bump
Add new istio versions for 1.8.5 & 1.9.3

Add istio 1.8.5 and 1.9.3

---

.github/PULL_REQUEST_TEMPLATE.md
images-list

1st commit: Sort current images in lexicographical order as they weren't in the correct order (Nothing was removed or added)
2nd commit: Add images for the vsphere CSI v2.2.0 update
Issue: https://github.com/rancher/rancher/issues/31105
PR: https://github.com/rancher/charts/pull/1135

Add images for vsphere CSI v2.2.0 update

---

images-list

bump images for k8s 1.21

---

images-list

https://drone-publish.rancher.io/rancher/image-mirror/106/1/3 
Images weren't tagged and failed, sample msg: 
```
Line: gcr.io/google_containers/pause rancher/mirrored-pause 3.4.1
--
1630 | gcr.io/google_containers/pause rancher/mirrored-pause 3.4.1
1631 | time="2021-05-10T19:03:24Z" level=fatal msg="Error parsing image name \"docker://gcr.io/google_containers/pause:3.4.1\": Error reading manifest 3.4.1 in gcr.io/google_containers/pause: manifest unknown: Failed to fetch \"3.4.1\" from request \"/v2/google_containers/pause/manifests/3.4.1\"."
1632 | ===
1633 | Failed copying image for rancher/mirrored-pause
1634 | ===
1635 | gcr.io/google_containers/pause:3.4.1 has unknown schemaVersion
1636 | ===
1637 | Failed copying image for rancher/mirrored-pause
1638 | ===
```

correct source repo for autoscaler and pause

---

images-list

Version Bump
https://istio.io/latest/news/security/istio-security-2021-006/
https://istio.io/latest/news/security/istio-security-2021-005/

Add istio v1.8.6 & v1.9.5

---

images-list

New mirrored image
https://github.com/rancher/rancher/issues/31873
https://github.com/rancher/rancher/issues/31598
EIO ticket: https://github.com/rancherlabs/eio/issues/454
System-Charts PR: https://github.com/rancher/system-charts/pull/461
The following dockerHub repo is to be created to support this PR:
`rancher/mirrored-kubernetes-external-dns`

Add mirrored image for rancher-external-dns system-chart

---

images-list

Update Cilium from 1.9.6 to 1.9.8. Changelogs of the last two releases:
* https://github.com/cilium/cilium/releases/tag/v1.9.8
* https://github.com/cilium/cilium/releases/tag/v1.9.7
Ref: rancher/rke2#1099
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
Version bump
rancher/rke2#1099

cilium: Update to 1.9.8

---

images-list

Related PR: https://github.com/rancher/charts/pull/1250
Related Issue: https://github.com/rancher/rancher/issues/32519

Add Prometheus Adapter v0.8.4

---

images-list

New image, needed for k8s 1.22 and to test if we can now mirror 1:1 because of manifest support.
https://github.com/rancher/rancher/issues/33114

Add etcd v3.5.0

---

images-list

New images for k8s v1.21 addons updates
https://github.com/rancher/rancher/issues/31567#issuecomment-858754265
* Missing kube-dns because images for 1.18.0 are missing upstream.
* Calico was already added for 3.19.1

Flannel/CoreDNS/metrics-server update for v1.21

---

images-list

New image
https://github.com/rancher/rancher/issues/31567
According to https://github.com/kubernetes/k8s.io/pull/2118, only the node-cache image was bumped and released.

Add kube-dns node-cache 1.18.0

---

images-list

Version Bump
https://hub.docker.com/r/istio/istioctl/tags?page=1&ordering=last_updated&name=1.10.2
https://hub.docker.com/r/istio/istioctl/tags?page=1&ordering=last_updated&name=1.9.6
Need to include versions for most recent Istio releases

Include istio 1.9.6 & istio 1.10.2

---

images-list

Add mirrored image for idealista/prom2teams:3.2.2

---

images-list

Add image updates for vSphere CSI v2.2.1
Addresses CVEs (See references to issues below)

Add vSphere CSI v2.2.1 image updates

---

images-list

This image is used for kubernetes versions 1.19.10-1.19.13 and
1.20.6-1.20.9.
Adding missing version

Mirror coreos/flannel 0.13.0

---

images-list

Add istio 1.9.8 and 1.10.4

---

images-list

New image, version bump.
https://github.com/rancher/rancher/issues/34593

Add mirrored image for gatekeeper 3.6.0 and gatekeeper-crds 3.6.0

---

.github/PULL_REQUEST_TEMPLATE.md
images-list

New images for the vSphere CSI 2.3.0 update and vSphere CPI v1.21.0
https://github.com/rancher/rancher/issues/34630

Add images for CSI 2.3.0 and CPI v1.21.0

---

images-list

* Will need someone to create the **`rancher/mirrored-ingress-nginx-kube-webhook-certgen`** repo on Docker Hub
new image
* https://github.com/rancher/rke2/issues/1892

Add forked kube-webhook-certgen v1.0

---

images-list

* New image:  quay.io/calico/apiserver rancher/mirrored-calico-apiserver v3.20.1
* Few Version bumps to v3.20.1 and operator to v3.20.3
https://github.com/rancher/rke2/issues/1892

New image and a few version bumps

---

images-list

add a new tag for `rancher/mirrored-prometheus-operator-prometheus-operator` used by monitoring v2
Issue: https://github.com/rancher/rancher/issues/34577

mirror image for monitoring v2 

---

images-list

Required as 3.6 is the first version to add support for Windows Server 2022.
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>
Version pump to the Pause image since 3.6 is the first version to add Windows support.
* https://github.com/rancher/windows/issues/104

Adding Pause 3.6

---

.drone.yml
image-mirror.sh

VERIFIED that images that do not contain s390x archs are not affected. [http://35.180.252.184/ivan-claire/image-mirror/8](in this test drone CI)

Create mirror images for s390x Arch

---

images-list

Add mirrored image for gatekeeper 3.7.0 and gatekeeper-crds 3.7.0

---

images-list

This request is adding a new image to mirror for the sigwindowstools GMSA webhook.
* https://github.com/rancher/windows/issues/22
Signed-off-by: Jamie Phillips <jamie.phillips@suse.com>

Adding mirror for sigwindowstools GMSA Webhook image.

---

images-list

Version bump for library/traefik:2.5.6 -> 2.6.0
Related to https://github.com/k3s-io/k3s/pull/5069

Update traefik to 2.6.0

---

image-mirror.sh

script update
@Oats87 
Chris noted that the script was causing the "last changed" time on the manifest lists to get updated every time the script runs. This is because we were rewriting the manifest list every time the script is run, even if we didn't sync any new images.
This change compares the digests in the new manifest list to those in the current manifest list (if any) and only pushes the manifest list if they do not match.

Don't update the manifest list if the list of images it refers to hasn't changed

---

images-list

Add new image for CPI
https://github.com/rancher/rancher/issues/33848
https://github.com/rancher/vsphere-charts/pull/3#pullrequestreview-880745772

Add image for CPI 1.1.0 (Support for K8s 1.22)

---

images-list

Adding the latest 2.5.1 images.
* https://github.com/rancher/rancher/issues/37005

Updating CSI images to 2.5.1

---

images-list

Version bumps for vSphere cloud provider images.
* https://github.com/rancher/rancher/issues/37004

Updating vSphere CPI images to pull in bugfix releases.

---

.drone.yml
images-list
images-list-daily

Solution for: https://github.com/rancherlabs/eio/issues/921
The goal of this PR is to add a pipeline step which will sync "latest" style images every day. They are in a separated list, and will run on push and [cron triggers](https://docs.drone.io/pipeline/docker/syntax/trigger/).
I ran the validator and daily steps locally, but I can't test for real without the credentials.

Add a daily image-mirror pipeline

---

images-list

Image can be found here: https://quay.io/repository/kiwigrid/k8s-sidecar?tab=tags&tag=latest
Current images can be found in https://hub.docker.com/r/rancher/mirrored-kiwigrid-k8s-sidecar/tags. Latest is 1.12.3

Mirror latest kiwigrid-k8s-sidecar for multi-namespace support for Project Monitoring V2

---

images-list

Adding updated vSphere CSI image to officially support K8s 1.23 and 1.24 with skew policy.
* https://github.com/rancher/rancher/issues/37319

Updating the vSphere CPI image to 1.23.0

---

images-list

New images for logging-operator 3.17.7

Add images for logging-operator 3.17.7

---

images-list

New images to mirror for integration of [Epinio](https://github.com/orgs/epinio) with the Rancher Marketplace.
Epinio ticket https://github.com/epinio/epinio/issues/1248
Rancher PR https://github.com/rancher/charts/pull/1814
General discussion about the work is on #epinio-appsmarketplace-integration
Main contacts @PennyScissors and @SheilaghM

Epinio 1248 add to Marketplace

---

images-list

Version bump for banzaicloud/logging-operator from 3.17.4 to 3.17.7
Related to issue: https://github.com/rancher/rancher/issues/36638 and pr: https://github.com/rancher/charts/pull/1999 in regards to backporting a new version of rancher-logging to 2.5.

Added banzaicloud/logging-operator:3.17.7 to image mirror list

---

images-list

Followup on https://github.com/rancher/image-mirror/pull/239
New images for the bump of epinio to v1.0.0.
See https://github.com/rancher/charts/pull/1814

bump images for epinio v1

---

images-list

New images (tags of existing bases): 
- `rancher/mirrored-epinio-epinio-server v1.2.0`
- `rancher/mirrored-library-nginx 1.23.0-alpine`
- `rancher/mirrored-library-registry 2.8.1`
Ref: https://github.com/rancher/charts/pull/1814
Ref: https://github.com/epinio/epinio/issues/1248#issuecomment-1213074682

epinio 1.2.1 chart: supporting images

---

images-list

New images (tags of existing bases):
rancher/mirrored-epinio-epinio-ui v1.2.0-0.0.1
Image was forgotten in PR #283. :(
Linked Issues
Ref: https://github.com/rancher/charts/pull/1814
Ref: https://github.com/epinio/epinio/issues/1248#issuecomment-1213074682

epinio 1.2.1 chart: supporting images, part 2 (forgotten ui image)

---

images-list

New images (tags of existing bases):
- `rancher/mirrored-epinio-epinio-unpacker 1.0`
Note: https://github.com/rancherlabs/eio/issues/1309 is the EIO PR asking for the creation of a `rancher/mirrored-epinio-epinio-unpacker` repository
Ref: https://github.com/rancher/charts/pull/1814
Ref: https://github.com/epinio/epinio/issues/1248#issuecomment-1213074682

epinio 1.2.1 - get the bash working for our staging

---

images-list

add new image for vSphere CSI chart upstream v2.6.1

---

images-list

add new tags for vsphere CSI chart upstream v2.5.3 and v2.4.3

---

images-list

Additional/New version for existing image
See https://github.com/rancherlabs/image-scanning/issues/1454 for origin

bump aws-cli image used by epinio

---

images-list

New images
* CSI release driver and syncer: v2.5.4, v2.6.2, v2.7.0
* CPI release manager: v1.24.2, v1.25.0
https://github.com/rancher/rancher/issues/38188

Update CSI and CPI mirror images list

---

images-list

Additional/New version for existing image
See https://github.com/rancherlabs/image-scanning/issues/1590 for origin of request

security: bump aws cli version

---

images-list

new image
* https://github.com/k3s-io/k3s/issues/2865
EIO repo creation request:
* https://github.com/rancherlabs/eio/issues/1377

Add images for kubernetes-csi/external-snapshotter

---

images-list

Updated image tags for enhanced security
- https://github.com/rancherlabs/image-scanning/issues/1458
- https://github.com/rancherlabs/image-scanning/issues/1459
- https://github.com/rancherlabs/image-scanning/issues/1460
- https://github.com/rancherlabs/image-scanning/issues/1461
- https://github.com/rancherlabs/image-scanning/issues/1666

Bump various epinio images (aws, nginx, paketo, and minio) to reduce amount of CVEs

---

images-list

New images for Epinio 1.5.1
- `epinio-server`, new tag
- `epinio-ui`, new tag
- `skopeo/stable`, new image
See https://github.com/rancher/charts/pull/2247
Requisites for merging this PR

Added images required for Epinio 1.5.1 and dependencies

---

image-mirror.sh

Fix mirroring manifest.v1 images
I don't think we had any of these before the recently-added cilium-etcd-operator image or we would have noticed that it is not pushing the manifest list to the base tag.
bugfix
Check https://hub.docker.com/r/rancher/mirrored-cilium-cilium-etcd-operator/tags

Fix mirroring manifest.v1 images

---

images-list

Add version 3.17.10 for banzaicloud/logging-operator.

Add banzaicloud/logging-operator v3.17.10

---

.drone.yml

Only allow Drone to run the pipeline once at the same time, to avoid conflicting tasks. Also avoids the "wait to merge til the previous pipeline run completes" which I doubt even everyone knows.

Run max 1 pipeline at a time

---

images-list

Version bump for images:
```
quay.io/cilium/clustermesh-apiserver:v1.12.5
quay.io/cilium/hubble-relay:v1.12.5
quay.io/cilium/hubble-ui:v0.10.0
quay.io/cilium/hubble-ui-backend:v0.10.0
quay.io/cilium/operator-aws:v1.12.5
quay.io/cilium/operator-azure:v1.12.5
quay.io/cilium/operator-generic:v1.12.5
quay.io/cilium/startup-script:5e928f628f9fc644a1d2651d6cd6aecbde0e7acd
```

Add newer cilium images

---

images-list

Images for Epinio 1.6.1
|Name|Version|
|---|---|
|aws-cli|2.9.14|
|epinio-server|1.6.1|
|epinio-unpacker|1.6.1|
|paketobuildpacks|0.2.298-full|
|minio,mc|5.0.4 (chart version)|
https://github.com/epinio/epinio/issues/2036

Added images required for Epinio 1.6.1 and dependencies

---

images-list

Followup to #338. A bad image tag was not caught before merge.
Slipped through my pull check also. Apologies.
- #338
- https://github.com/epinio/epinio/issues/2036

fixup for new epinio unpacker image, bad tag slipped through

---

images-list

New epinio release 1.6.2. No changes to dependencies.
- Release: https://github.com/epinio/epinio/releases/tag/v1.6.2
- Chart use: https://github.com/rancher/charts/pull/2401

epinio 1.6.2 images

---

images-list

Upstream flannel is now published in flannel/flannel instead of flannelcni/flannel so the source repo changes starting with this version.
The new target repository `rancher/mirrored-flannel-flannel` has been created: https://hub.docker.com/r/rancher/mirrored-flannel-flannel

add flannel/flannel v0.21.2

---

scripts/image-mirror.sh

Currently, the image still gets processed even if the `skopeo inspect` returns an error. This should save time and allow us to grep the log files more easily to find non-existent images (to clean up)

Do not proceed if image/manifest does not exist

---

images-list
scripts/check-new-images-exist.sh

Checked with @andreas-kupries, tag `0.7.1` was never mirrored and `v0.7.1` does exist. Decision was to correct it so any potential usage of `v0.7.1` is going to work.
Also included a fix to the check script to ignore removed images.

Correct tag for epinio-server:v0.7.1

---

images-list

version bump
* https://github.com/rancher/rke2-charts/pull/303

Bump sig-storage-snapshot tags

---

images-list

See https://github.com/coredns/coredns/issues/4418 and https://github.com/rancher/rancher/issues/30134#issuecomment-769556753
It has never been mirrored, does not exist in our Docker Hub.

CoreDNS 1.8.1 was never properly released/mirrored

---

images-list

Tag `RELEASE.2020-07-13T18-09-56Z` was released for `minio/minio` (see https://github.com/minio/minio/releases/tag/RELEASE.2020-07-13T18-09-56Z) but never for `minio/mc` (see non existent tag https://github.com/minio/mc/releases/tag/RELEASE.2020-07-13T18-09-56Z).
It also has never been mirrored (https://hub.docker.com/r/rancher/mirrored-minio-mc/tags)
Checked with @andreas-kupries

Cleanup non existent minio/mc tag

---

images-list

This image does not exist in quay.io, it was added in [a k8s 1.25 PR](https://github.com/rancher/image-mirror/commit/8f58c79b73261ed6437e65cb5908acea0917c1f8) and corrected to the correct image in [this KDM PR](https://github.com/rancher/kontainer-driver-metadata/commit/c4a687bbfbb527559a0264231e2afb7391f65ec8#diff-946512550baddbb48e0b41424179a72358b7d614165c87b1eb0bf0b09cd617d2R8389).
v0.19.2 has also never been mirrored at `rancher/mirrored-coreos-flannel` (https://hub.docker.com/r/rancher/mirrored-coreos-flannel/tags)
Checked with @jiaqiluo

Cleanup non existent flannel tag v0.19.2

---

CODEOWNERS

Having the group as automatically requested reviewer will reduce review noise as it will be cleared from the other reviewers as soon as someone approves it.

Use CODEOWNERS group to reduce review noise

---

images-list

Signed-off-by: Derek Nola <derek.nola@suse.com>
The ingress-nginx/kube-webhook-certgen avaliable is old, last published 8 months ago. The tag is weird becuase upstream no longer published versioned tags, they are based off commit now. 
This is needed for rke2 charts to support the latest hardened ingress-nginx controller. 
This is the last of the `k8s.gcr.io` for this image, future bumps will need to be moved to `registry.k8s.io`.

Add latest ingress-nginx/kube-webhook-certgen tag

---

images-list
retrieve-image-tags/config.json

version bump
https://github.com/k3s-io/k3s/issues/7301

Bump traefik tag and add action config to auto-bump

---

images-list

Signed-off-by: Derek Nola <derek.nola@suse.com>
Bump to add newest tags of vsphere csi and cpi images

Add latest CPI CSI tags

---

images-list

bump k8s pause to 3.9
https://github.com/rancher/rancher/issues/41113

bumped k8s pause to 3.9

---

images-list

`rancher/mirrored-library-nginx` version bump to `1.24.0-alpine`
https://github.com/rancher/charts/pull/2589

add tag 1.24.0-alpine for nginx

---

.github/workflows/validate-retrieve-image-tags-config.yml

Adds validation to PRs created that modify `retrieve-image-tags/config.json`:
- Valid JSON
- It can be executed successfully and output can be checked

Add workflow to validate retrieve-image-tags cfg

---

images-list

Bump 1.24 and 1.25 vsphere cpi for golang/x/net CVE fix

---

scripts/check-new-images-exist.sh

Add check if target repository exists, only if its a new target repository (this check is ignored if its not a new target repository)
https://github.com/rancher/image-mirror/issues/399

Expand check script to check for target repository

---

images-list

New images for updated Epinio chart in Rancher Marketplace. (Bump to 1.8.1)
Ref https://github.com/epinio/epinio/issues/2326
Ref https://github.com/rancher/charts/pull/2670 (blocked by this ticket)
:heavy_check_mark:  https://github.com/rancherlabs/eio/issues/1647 . __Can be merged now__

New images for Epinio 1.8.1 and sub-charts.

---

images-list-daily

New tags for existing images 
https://github.com/rancher/rancher/issues/40908
The tag `latest` is used in the `rancher-vsphere-csi` and `rancher-vsphere-cpi` charts ([PR](https://github.com/rancher/vsphere-charts/pull/55)). 
Note that the `latest` tags are actually not used, and here is why:
In the vSphere chart, the image tags are overwritten by the `versionOverrides` directives based on the cluster k8s version in the value.yaml file ( [here](https://github.com/rancher/vsphere-charts/blob/main/charts/rancher-vsphere-csi/values.yaml#L140C9-L140C9) and [here](https://github.com/rancher/vsphere-charts/blob/main/charts/rancher-vsphere-cpi/values.yaml)) . And the "latest" tag is only used when the chart is installed into a cluster whose version is NOT in the supported range, as [the comment …

add the latest tag for images used in the rancher-vsphere-csi and rancher-vsphere-cpi charts

---

images-list

version bump
https://github.com/rancher/rke2/issues/4417

Update calico to 3.26.1 and cilium to 1.13.4

---

images-list

- [ X ] Change does not remove any existing Images or Tags in the images-list file
- [ X ] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X ] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X ] New entries are in format `SOURCE DESTINATION TAG`
- [ X ] New entries are added to the correct section of the list (sorted lexicographically)
- [ X ] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ X ] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF …

Update neuvector release images to 5.2.0

---

README.md
retrieve-image-tags/config.json
retrieve-image-tags/retrieve-image-tags.py

Adds configuration to automatically create PRs for calico and cilium required images
Because `quay.io/cilium/startup-script` uses a commit hash, I added `latest_entry` as a new config option to just return the first tag in the list.
@rbrtbnfgl can check if the configuration is good regarding source/destination and tags, output can be checked in https://github.com/rancher/image-mirror/actions/runs/5531007770/jobs/10091127096?pr=414#step:6:13

Add calico/cilium to auto PR configuration

---

images-list

- [ X] Change does not remove any existing Images or Tags in the images-list file
- [ X] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X] New entries are in format `SOURCE DESTINATION TAG`
- [ X] New entries are added to the correct section of the list (sorted lexicographically)
- [ X] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ X] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved …

Correct neuvector prometheus exporter mirror image name

---

images-list

version bump
* https://github.com/rancher/rke2/issues/4549

Add registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.2

---

images-list
retrieve-image-tags/config.json

New images for Cilium and flannel cni-plugin.
For `cilium-envoy` there isn't a proper way to get the latest release.

Added new Cilium images and flannel cni plugin

---

images-list

Removing images which do not have repo created

---

images-list

version bump
https://github.com/rancher/rancher/issues/41840

add flannel v0.22.2

---

Dockerfile.dapper

Bump skopeo version to `v1.13.2` in Dockerfile.dapper because the image version `v1.1.1` was deleted upstream. Please refer to the snapshot below. 
Because of this the CI for mirror image failed. See https://drone-publish.rancher.io/rancher/image-mirror/961

Bump skopeo image to v1.13.2

---

.github/workflows/retrieve-image-tags.yml

Solves the issue that PR gets recreated if closed, by looking for states when retrieving existing PRs. When it is already created, we don't create a new one. If you want a new PR, you can rename the existing PR so it doesn't get found by the script and it will create a new PR.

Check existing PR with all states when adding tags

---

retrieve-image-tags/config.json

This will be solved when we implement https://github.com/rancher/image-mirror/issues/437, for now there are just too many new tags for this image.
Also see https://github.com/rancher/image-mirror/pull/433

Remove cilium-envoy because too many new tags

---

scripts/image-mirror.sh

[The bump](https://github.com/rancher/image-mirror/pull/456) to a newer version of `skopeo` seems to cause issues with authentication, as there are lots of `toomanyrequests` and access errors in the log.
It seems to no longer use the auth file created by `docker login`, and although we could point to it, we might as well just use the "native" `skopeo login` to make sure it will use whatever `skopeo` requires to work.

Authenticate using skopeo to avoid rate limit

---

images-list

Version bump for kube-rbac-proxy `0.5.0` -> `0.14.0`
https://github.com/rancher/rancher/issues/42019
https://github.com/rancher/charts/pull/2785

bump kube-rbac-proxy

---

images-list

updating kiali version from 1.72 -> 1.74

---

images-list

Added the envoy image required for cilium 1.14.2 https://github.com/rancher/rke2/pull/4837

Update Cilium envoy image for cilium v1.14.2

---

images-list

Bump up neuvector product version to 5.2.2

---

images-list

add images for monitoring rebase to prometheus 45.31.1

---

images-list

https://github.com/rancher/charts/pull/3030

bump images for rancher-monitoring/rancher-grafana rebase

---

images-list

version bump
* Multiple CVEs in busybox <1.35; ref https://github.com/k3s-io/k3s/issues/8373

Bump busybox to v1.36.1

---

images-list

These are new images
https://github.com/rancher/charts/pull/3104
Our source images are coming from `registry.suse.com/rancher/[elemental-operator,seedimage-builder]`.
To my understanding, images mirrored here are loaded to `rancher` docker hub and then mirrored to registry.suse.com for Rancher PRIME. My guess at this point is that if we mirror `registry.suse.com/rancher/elemental-operator`  to `rancher/elemental-operator` it would be awesome on `rancher` in Docker Hub but some issues may happen when mirroring the images from docker hub to registry.suse.com as the repo name will be already taken.
Is there a way to skip the mirroring back to PRIME?
For now in the PR I put the "mirrored-elemental-operator" as the image name, so that the PRIME mirroring will end up in …

Add Elemental images

---

images-list

- `docker.io/rancher/mirrored-coreos-node-exporter` never existed?  See list below what has been used:
```
prom/node-exporter rancher/mirrored-prom-node-exporter v1.0.1
prom/node-exporter rancher/prom-node-exporter v1.0.1
quay.io/prometheus/node-exporter rancher/mirrored-prometheus-node-exporter v1.1.2
quay.io/prometheus/node-exporter rancher/mirrored-prometheus-node-exporter v1.2.2
quay.io/prometheus/node-exporter rancher/mirrored-prometheus-node-exporter v1.3.1
```
- `docker.io/banzaicloud/fluentd` tags no longer exist
```
time="2023-10-16T16:23:40Z" level=fatal msg="Error parsing image name \"docker://docker.io/banzaicloud/fluentd:v1.11.2-alpine-2\": reading manifest v1.11.2-alpine-2 in docker.io/banzaicloud/fluentd: requested access to the resource is denied" …
```

Cleanup non-existent images/repository

---

retrieve-image-tags/config.json

Based on https://github.com/rancher/image-mirror/pull/488#issuecomment-1761712417, this restricts the tags to just what we need. We have a closed PR today and it won't open a new one, but with new images coming in, there will be new PRs where these versions will still be included as they are matched in the filter. This PR changes the filter to v1.24.x and up.

Restrict cpi tags to supported versions

---

.github/workflows/validate-retrieve-image-tags-config.yml
README.md
retrieve-image-tags/retrieve-image-tags.py

First part of https://github.com/rancher/image-mirror/issues/500
I went back and forth on this implementation, I started with a `devel` configuration option at first (like in this PR) but felt like maybe it could be more generic. So I transformed it into `helmArgs` but after implementing it, it didn't really make sense as it would not consume global Helm args but specific args for subcommands. And wether we need specific configuration directives for `helm template` and `helm show values`, we'll see in the future. 
For now,  this adds the option to use development versions (mainly used for local testing for now)

Add devel configuration option

---

images-list

needed for nginx v1.9.4
version bump for ingress-nginx/kube-webhook-certgen. new version v20231011-8b53cabe0 is added which is present in nginx-v1.9.4 manifest [ref](https://github.com/kubernetes/ingress-nginx/blob/5583f90c7f3525b6267747d6b07541c01218a9ea/deploy/static/provider/cloud/deploy.yaml#L591)
https://github.com/rancher/rancher/issues/43204 and https://github.com/rancher/rancher/issues/43205

bump ingress-nginx/kube-webhook-certgen to v20231011-8b53cabe0

---

README.md
retrieve-image-tags/config.json
retrieve-image-tags/retrieve-image-tags.py

https://github.com/rancher/image-mirror/issues/506
This adds two options to filter versions, one to include additional versions to a PR and one to specify a version (filter).
Because I was testing with Longhorn, I also optimized getting images from `helm show values` as the chart nested the images 3 levels deep and the code only looked 2 levels. I added a function that recursively walks through the dict. This also found 2 new images in cilium chart that I added to the `imageDenylist`

Add additional version options

---

images-list

- [+] Change does not remove any existing Images or Tags in the images-list file
- [+] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [+] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [+] New entries are in format `SOURCE DESTINATION TAG`
- [+] New entries are added to the correct section of the list (sorted lexicographically)
- [+] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [+] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved …

Bump up neuvector product version to 5.2.3

---

images-list

Longhorn longhorn/longhorn#7082
Rancher rancher/rancher#43566, rancher/rancher#43567

docs(longhorn): Add longhorn 1.5.3 images

---

retrieve-image-tags/config.json

added version constraint for etcd image in retrieve images tags config

added version constraint for etcd in retrieve image tags config

---

retrieve-image-tags/retrieve-image-tags.py

The chart_values and kube_version are undefined
https://github.com/rancher/image-mirror/issues/541

Fix bug which crash the script retrieve-image-tags.py

---

README.md
retrieve-image-tags/config.json
retrieve-image-tags/retrieve-image-tags.py

Longhorn would like to automate adding/mirroring images. However, the currently available list of data sources don't fit the use-case of Longhorn:
1. `github-releases` data source: This one finds new GitHub release tag and adds the images defined in the `images` field in the `config.json` file. For example:
```json
{
"vsphere-cpi": {
"images": [
"gcr.io/cloud-provider-vsphere/cpi/release/manager"
],
"versionSource": "github-releases:kubernetes/cloud-provider-vsphere",
"versionConstraint": ">1.21.0"
}
}
```
This `config.json` file instructs the script to find GitHub release tags in the repo `kubernetes/cloud-provider-vsphere`. Then only add the `gcr.io/cloud-provider-vsphere/cpi/release/manager` image with the found tags to the [images-list](https://github.com/rancher/image-mirror/blob/mast …

[Improvement] Add a new data source, github-tagged-images-file, to automate retrieving images from a image-list file of a GitHub release

---

images-list

* Added the following new tags:
* flannel/flannel v0.24.2
* calico/ctl v3.27.0
* calico/kube-controllers v3.27.0
* calico/node v3.27.0
* calico/pod2daemon-flexvol v3.27.0
* cluster-api/cluster-api-controller v1.5.5
* https://github.com/rancher/rancher/issues/43109

[v1.28] Add new tags for flannel, calico and cluster-api

---

images-list

New image for rancher-logging logging-operator. Logging operator ownership has changed so we will need a new repo for `rancher/mirrored-kube-logging-logging-operator`

add new image for logging rebase

---

images-list
retrieve-image-tags/config.json

This adds the new image for calico needed for the csi-node-driver

Added new image node-driver-registrar for calico

---

images-list

version bump of elemental images
https://github.com/rancher/elemental/issues/1221

Added tag v1.4.2 for elemental images

---

images-list

* Add kube-webhook-certgen `v20231226-1a7112e06`, [context](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.9.6).
* https://github.com/rancher/rancher/issues/43109

[v1.28] Add kube-webhook-certgen v20231226-1a7112e06

---

images-list

- [x Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
New tag for image: `registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2`
Issue: https://github.com/rancher/rancher/issues/41321
PR in vsphere-charts: https://github.com/rancher/vsphere-charts/pull/68

add sig-storage csi-snapshotter 6.2.2

---

images-list

Version bump (2.45 is the most recent LTS)
https://github.com/rancher/rancher/issues/44605

Add rancher/mirrored-prometheus-prometheus v2.45.0

---

scripts/check-new-images-exist.sh
scripts/image-mirror.sh

Script Update
This PR updates the `check-new-images-exist.sh` script to handle Windows only images. By default, `skopeo inspect` will [attempt to find an image supporting the platform the command is run on](https://github.com/containers/skopeo/blob/main/docs/skopeo-inspect.1.md#description) (e.g. `linux/amd64`). For the vast majority of Docker containers this is not a problem, however for Windows only containers this check will obviously fail. 
After this PR, when processing an image which does not contain a `linux/amd64` entry, `check-new-images-exist.sh` will call `skopeo inspect --override-os windows` before declaring that the image does not exist. 
Note that this problem only occurs with the `check-new-images-exist.sh` script. The `image-mirror.sh` script will successfully mirror …

Handle images which only support Windows

---

images-list

- [EIO Ticket](https://github.com/rancherlabs/eio/issues/2102), [Docker Hub Repo](https://hub.docker.com/r/rancher/mirrored-prometheus-windows-exporter)
- [This image uses an MIT license](https://github.com/prometheus-community/windows_exporter/blob/master/LICENSE)
- Will be updated in rancher/rancher before https://github.com/rancher/charts/pull/3607 is merged
New Image
https://github.com/rancher/windows/issues/234

add rancher/mirrored-prometheus-windows-exporter 0.25.1

---

images-list

https://github.com/rancher/charts/pull/3753
longhorn/longhorn#8329

Update missing image for Longhorn 1.6.1 Rancher chart release

---

images-list

registry.suse.com/rancher/elemental-operator:1.4.3
registry.suse.com/rancher/seedimage-builder:1.4.3

Adding Elemental 1.4.3 images

---

retrieve-image-tags/config.json

This PR moved the image tags check for `tigera-operator` to the one defined on the latest calico chart.

Moved tigera-operator image tag to the one defined on the chart

---

images-list

As part of 1.29 support
- bumped etcd to `v1.6.4`
- https://github.com/rancher/rancher/issues/43110

[v1.29] Add cluster-api v1.6.4

---

images-list

new version of pause image from k8s has been released (registry.k8s.io/pause:3.10). Ref: https://github.com/kubernetes/k8s.io/pull/6840

bump pause to 3.10

---

images-list

registry.suse.com/rancher/elemental-operator:1.5.3 registry.suse.com/rancher/seedimage-builder:1.5.3

Adding Elemental 1.5.3 images

---

images-list

added metrics server v0.7.1 image.
https://github.com/rancher/rancher/issues/45089
bumping metrics server to use the latest version([v0.7.1](https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.7.1)) with k8s 1.30 version in rke.

added metrics server v0.7.1 image

---

images-list

- Added images for `vsphere-cpi-release-manager: v1.29.0`
- Added images for `vsphere-csi` version v3.2.0 support images
- https://github.com/rancher/rancher/issues/45463
- https://github.com/rancher/rancher/issues/45464

vsphere 1.29 support

---

images-list

Addresses part of https://github.com/rancherlabs/image-scanning/issues/1366

Add tag for fluentd image

---

images-list

bump cluster-api-controller to v1.7.2
https://github.com/rancher/rancher/issues/45089

added cluster-api-controller v1.7.2

---

images-list

https://github.com/rancher/rancher/issues/45089
for nginx 1.10.1 the kube webhook cert-gen image is updated. [ref](https://github.com/kubernetes/ingress-nginx/blob/51847ac1b537c547cdb7bfb06d14e6d3d8476a73/charts/ingress-nginx/values.yaml#L801-L805)

added ingress-nginx-kube-webhook-certgen v1.4.1

---

images-list

- Added images for `vsphere-cpi-release-manager: v1.30.1`
- https://github.com/rancher/rancher/issues/45746

added images for vsphere-cpi 1.30.0 support

---

images-list

bump cluster-api-controller to v1.7.3
https://github.com/rancher/rancher/issues/45089

added cluster-api-controller v1.7.3

---

images-list

New image `rancher/mirrored-prometheus-operator-admission-webhook`.
Bumping versions for prometheus-operator.
* https://github.com/rancher/rancher/issues/44614

Bump prometheus-operator images

---

images-list

bump bci image versions

---

Dockerfile.dapper

This reverts commit c402a5abad87ac7da57a3dd9620f10e1815dcfe2.
Dapper is still used in the validate-retrieve-image-tags-config.yml GitHub action so reverting the removal of the Dapper Dockerfile.

Revert "chore: Remove unused Dockerfile.dapper"

---

images-list

registry.suse.com/rancher/elemental-operator:1.5.4 registry.suse.com/rancher/seedimage-builder:1.5.4

Adding Elemental 1.5.4 images

---

images-list

https://github.com/rancher/rancher/issues/46035
https://github.com/rancher/charts/pull/4235

bump kube-logging operator image

---

images-list

New image tag
[#1366](https://github.com/rancherlabs/image-scanning/issues/1366)

include fluentd latest base build

---

images-list

Update to latest cpi/csi image tags for K8s 1.31

---

.github/workflows/ci.yml

This change prevents redundant Actions running on a PR.
Given a situation where a PR has been created and gets updates pushed. Each update will trigger a new CI workflow to run, however only the most recent one is actually valid for the current state. As such this change will prevent the redundant jobs from running, cancelling them without error, and will allow the correct workflow to run sooner.
CI Tweaks
N/A; just something I noticed could benefit from this setting while crafting a PR.
N/A

Adjust CI job for concurency

---

images-list

https://github.com/rancherlabs/image-scanning/issues/2566

bump kube-webhook-certgen version

---

images-list

registry.suse.com/rancher/elemental-operator:1.6.4
registry.suse.com/rancher/seedimage-builder:1.6.4

Adding Elemental 1.6.4 images

---

images-list

New image to be used by rancher-logging.
The logging-operator has moved from https://github.com/jimmidyson/configmap-reload in favor of https://github.com/kube-logging/config-reloader, as can be seen [here](https://github.com/kube-logging/logging-operator/blob/f8081b7bdbd2622820d2384fbe86b58873dc8db2/pkg/sdk/logging/api/v1beta1/logging_types.go#L172). We need to keep our image dependencies up to date with upstream.
https://github.com/rancher/rancher/issues/46924

add new config-reloader image

---

images-list

longhorn/longhorn#9346
rancher/rancher#47182, rancher/rancher#47183, rancher/rancher#47184

docs(longhorn): Add longhorn 1.7.1 images

---

images-list
retrieve-image-tags/config.json

new tag for external-snapshotter images

---

images-list

Add new(?) kube-webhook-certgen tag

---

images-list

- [n/a] New entries, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
Version bump for xx image
n/a; just bumping as it's used in some build processes
This image doesn't end up part of rancher origins, just used as part of build pipeline in various docker images.

Add tonistiigi/xx:1.5.0 image

---

.github/workflows/add-tag-to-existing-image.yml

Removes dapper from GHA workflows by calling the scripts directly.
Follow up for:
https://github.com/rancher/image-mirror/pull/668
https://github.com/rancher/image-mirror/pull/669
Will fix: https://github.com/rancher/image-mirror/issues/666

Remove dapper from GHA calls

---

images-list

registry.suse.com/rancher/elemental-operator:1.6.5
registry.suse.com/rancher/seedimage-builder:1.6.5

Adding Elemental 1.6.5 images

---

images-list
retrieve-image-tags/config.json

Bump kubevip and add to auto-pr

---

images-list

https://github.com/rancher/rancher/issues/47783

New image tags for logging rebase to 4.10.0

---

images-list

- [n/a] New entries are in format `SOURCE DESTINATION TAG`
- [n/a] New entries are added to the correct section of the list (sorted lexicographically)
- [n/a] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [n/a] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [n/a] New entries, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
- [n/a] Changes to scripting or CI config …

Add new image tags need for monitoring 105.2.0-rc.1+up65.5.1

---

images-list

adding images that will be used for rancher-istio 1.24

---

images-list

Previous PR mirrored these images to the wrong repo
https://github.com/rancher/rancher/issues/47911

add fluent-bit windows images to correct repository

---

images-list

Add kube-webhook-certgen v1.5.0

---

retrieve-image-tags/config.json

automated version bump
* https://github.com/k3s-io/k3s/issues/10526

Add auto-update for latest traefik3 image

---

images-list

New Image
Related tot his PR: https://github.com/rancher/ob-team-charts/pull/9

add kube-state-metrics:v2.14.0

---

images-list

- [n/a] Changes to scripting or CI config have been tested to the best of your ability
Version Bumps for new charts

add new kube-rbac-proxy and prometheus-operator-admission-webhook

---

images-list

adding images needed for istio 1.25

---

.github/workflows/mirror-images-regsync.yml
.github/workflows/pull-request.yml
config.yaml
regsync.yaml
tools/main.go
tools/main_test.go
tools/pkg/config/config.go

Also:
- Add a workflow for running `golangci-lint` and `go test` on Go code during PR checks.
- Simplify user/password/registry settings in `config.yaml`.
Until we are more confident in these changes, regsync-based mirroring can only be triggered via a `workflow_dispatch` event.

Add github actions workflow for mirroring images using regsync

---

config.yaml
regsync.yaml
tools/.golangci.yaml
tools/main.go
tools/main_test.go
tools/pkg/config/accumulator.go
tools/pkg/config/config.go
tools/pkg/config/config_test.go
tools/pkg/legacy/config.go
tools/pkg/legacy/list.go

This PR is the first step towards https://github.com/rancher/rancher/issues/49869. It automates the process of migrating lines from `images-list` and `images-list-daily` to `config.yaml`.
This was an old branch that I wrote a month or two ago. At that time, my intent was to migrate all of the images in one go. However, it has become clear that we need to take a more granular approach. I've added a couple of commits onto the branch in order to facilitate this; `bin/image-mirror-tools migrate-images-list` now requires the source and target image (as specified in `images-list`) to be passed as arguments. Sorry for the confusion this may create when reviewing this PR.

Introduce code to automate migration of `images-list` and `images-list-daily`

---

images-list

Add version v1.9.0 for cluster-proportional-autoscaler

---

config.yaml
regsync.yaml

Prior to #876 `config.yaml` was contained demonstration images in order to make the scheme easier to understand for PR reviews. I removed these images in #876, but I think they got added back in a rebase. This PR removes these demonstration images.

Remove demonstration images from `config.yaml`

---

.github/workflows/mirror-images-regsync.yml

It looks like the regsync call in the regsync mirroring workflow needs to be
```
time ./regsync once --config --missing regsync.yaml
```
not
```
time regsync once --config --missing regsync.yaml
```
Otherwise, the shell cannot find `regsync`.
This is weird, because I did test this workflow from my personal repo when I initially developed it. Maybe this line got changed in a rebase? Anyhow, this PR fixes the problem.

Add "./" to regsync call so that regsync can be found

---

.github/workflows/mirror-images-regsync.yml

Looking at https://github.com/rancher-eio/read-vault-secrets, it looks like the secrets go into the `env` context, not the `secrets` context. This PR fixes this for the regsync image mirroring workflow.

Get secrets from `env` context, not `secrets` context

---

tools/internal/config/config.go

This PR introduces a new naming scheme for images that come from the appco. I think this is a good idea for two reasons:
1. Appco images have only one significant part in their reference. For example, in `dp.apps.rancher.io/containers/openjdk` `dp.apps.rancher.io` is the host, `containers` is the repository, and `openjdk` is the artifact name. This differs from images from docker hub and ghcr.io, where the last two parts of the URL (org and image name) are significant.
2. It is helpful to distinguish between images that come from "just anywhere" and images that come from the appco.
For example, the entry in `config.yaml`:
```yaml
- SourceImage: dp.apps.rancher.io/containers/openjdk
Tags:
- 21.0.7-build6
```
now produces, in `regsync.yaml`:
```yaml
- source: …
```

Use `appco-` prefix for default target image name when source image comes from appco

---

images-list

+ https://hub.docker.com/r/rancher/mirrored-gmsa-webhook-k8s-gmsa-webhook/tags
+ The charts which use this image are not included with Rancher by default. When / if the gmsa charts are pulled into rancher/charts PRs will be raised to appropriately include the origins.
Sync new upstream version.
https://github.com/rancher/rancher/issues/50063

Add new gMSA webhook tag v0.13.0

---

images-list

registry.suse.com/rancher/elemental-operator:1.6.8
registry.suse.com/rancher/seedimage-builder:1.6.8

Adding Elemental 1.6.8 images

---

README.md
config.yaml
regsync.yaml
tools/internal/config/config.go
tools/internal/regsync/config.go
tools/main.go

The idea here is to give us an option (speeding up mirroring) other than increasing the timeout when we start hitting the default 6 minute timeout on github actions jobs. This PR adds the necessary field (`ReqConcurrent`) to `config.yaml` so that it can be configured in `regsync.yaml`.
For the documentation for `creds.reqConcurrent` please see https://regclient.org/usage/regsync/.

Parallelize `regsync` mirroring

---

config.yaml
regsync.yaml
tools/internal/config/config.go
tools/main.go

Related to https://github.com/rancher/rancher/issues/50159.
`appscode/kubed` is causing the `regsync` mirroring workflow to fail. I think it is a good idea to keep an entry in `config.yaml` for `appscode/kubed` for future reference. So, I am adding the `DoNotMirror` field to `config.Image` so that we can omit an image from `config.yaml` from the generated `regsync.yaml`.

Add `DoNotMirror` field to `config.Image` and add it to `appscode/kubed`

---

config.yaml
regsync.yaml

Add new image tags
https://github.com/rancher/ob-team-charts/pull/76

Update Monitoring Images for https://github.com/rancher/ob-team-charts/pull/76

---

config.yaml
regsync.yaml

I believe that these images are causing the `regsync` mirroring workflow to fail. When I attempt to pull them via `docker pull`, I get an error looking like the following:
```
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/jetstack/cert-manager-controller:v0.8.1 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```
This PR omits them from the mirroring process.

Do not mirror `quay.io/cilium/cilium-etcd-operator` and `quay.io/jetstack/cert-manager-controller`

---

config.yaml
regsync.yaml

Part of https://github.com/rancher/rancher/issues/49870.
This PR disables mirroring for `registry.suse.com/rancher/elemental-operator:1.3.4`. For whatever reason, this tag (and only this tag; I tested the others using `docker pull`) of this image is not present on `registry.suse.com/rancher`. This should get the `regsync` mirroring workflow green again.

Do not mirror registry.suse.com/rancher/elemental-operator:1.3.4

---

tools/internal/config/accumulator.go
tools/internal/config/accumulator_test.go

Previously, `ImageAccumulator` indexed only on `SourceImage` and `TargetImageName`. This could lead to problems in cases like the one introduced in https://github.com/rancher/image-mirror/pull/932. This PR adds `DoNotMirror` to the indexed fields.

Fix `ImageAccumulator` indexing

---

config.yaml
images-list
regsync.yaml

This issue is part of https://github.com/rancher/rancher/issues/49870.
It migrates entries from `images-list` with source images starting with letters S-Z that are not mentioned in `retrieve-image-tags/config.json`.

Migrate `images-list` to `config.yaml` (S-Z)

---

config.yaml
regsync.yaml

registry.suse.com/rancher/elemental-operator:1.6.9
registry.suse.com/rancher/seedimage-builder:1.6.9

Adding Elemental 1.6.9 images

---

regsync.yaml
tools/main.go

Elemental container images are built directly (via IBS) in registry.suse.com.
In order to not mess-up with "classic" Rancher Prime sync process which cloned `docker.io/rancher/<IMAGE>` to `registry.suse.com/rancher/<IMAGE>`  we used `registry.suse.com/rancher/mirrored-<IMAGE>` as target for elemental images in `images-list` file.
The new process allows decoupling of syncs in docker.io and registry.suse.com. We can start then to have elemental-operator images cloned from registry.suse.com to docker.io and avoid the sync step from docker.io to registry.suse.com.
Still, the current Elemental images in the form "mirrored-elemental-*" are required in registry.suse.com, since those images are targeted by Rancher Prime Elemental chart deployments.
commit #b9cd2aee0944f761d8a620b6ca6580ad480802d3 …

Skip mirroring images when target and source image are exactly the same

---

.github/workflows/mirror-images-regsync.yml

This PR does two things:
1. Makes it possible to enable debug logging in the `regsync` step. This may help us solve issues in the future.
2. Updates `regsync`.

Update regsync mirroring workflow

---

config.yaml
regsync.yaml

[K8s-1.33]Added Capi v1.10.2

---

README.md
autoupdate.yaml
tools/internal/autoupdate/config_test.go
tools/internal/autoupdate/githublatestrelease.go
tools/internal/autoupdate/githublatestrelease_test.go

Fixes https://github.com/rancher/rancher/issues/50781.
Basically, whenever we are referring to an image in `config.yaml`, we must index on *both* `SourceImage` and `TargetImageName`. This will be a pattern in every autoupdate strategy.

Allow specifying `TargetImageName` in `GithubLatestRelease` images

---

tools/internal/autoupdate/helmlatest.go

I noticed an error in the autoupdate workflow: https://github.com/rancher/image-mirror/actions/runs/16074545116/job/45366540428
We were treating `foundTargetImageName == ""` as an error case. However, this is also the case when `sourceImage == autoupdateImageRef.SourceImage` but `autoupdateImageRef.TargetImageName` is unset. This PR fixes this by making `foundTargetImageName` a pointer to a string, and treating the `nil` case as unset.

Fix `HelmLatest` update strategy's treatment of `Images` key

---

README.md
tools/internal/autoupdate/config.go
tools/internal/autoupdate/config_test.go

Closes https://github.com/rancher/rancher/issues/51069.
See the linked issue for more information. We are keeping the `Reviewers` field (and the requirement to define it) because it says which teams own any given `autoupdate.yaml` entry.

Do not use `autoupdate.yaml` `Reviewers` field to request pull request reviews

---

config.yaml
regsync.yaml

Issue https://github.com/rancher/ob-team-charts/issues/101

add grafana image renderer v4.0.5

---

tools/main.go

https://github.com/rancher/image-mirror/pull/1046 is failing the PR check that runs `image-mirror-tools validate`. This check is failing because it involves pulling an image from the application collection, which requires authentication.
Ideally we would update `image-mirror-tools validate` and the `pull-request.yml` workflow to provide authentication to the application collection, but this requires secrets to be fetched via `rancher-eio/read-vault-secrets`. And that requires `id-token: write` permissions, which cannot be granted to workflows triggered by pull requests from forks for security reasons: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflows-in-forked-repositories.
Instead, this pull request disables the image pulling check …

Do not try pulling new image tags if they are from the application collection

---

autoupdate.yaml
config.yaml
regsync.yaml

Add metrics-server v0.8.0

---

autoupdate.yaml

fixup for 52250a0648884e4ff08933b877ff0f7a482f17ff
resolves: https://github.com/rancher/image-mirror/pull/1059#discussion_r2261668302

metrics-server: Add missing `TargetImageName` to autoupdate.yaml

---

config.yaml
regsync.yaml

Request for EIO to create dockerhub repo: https://github.com/rancherlabs/eio/issues/3533
This is part of https://github.com/rancher/rancher/issues/51341.

Mirror dp.apps.rancher.io/containers/k8s-sidecar:1.30.7-11.3

---

config.yaml
regsync.yaml

Harvester issue: https://github.com/harvester/harvester/issues/5670
PR: https://github.com/harvester/charts/pull/404
To replace those pending/out-dated PRs:
https://github.com/rancher/image-mirror/pull/988
https://github.com/rancher/image-mirror/pull/1053
https://github.com/rancher/image-mirror/pull/976
local test:
```
docker pull ghcr.io/kube-vip/kube-vip-iptables:v0.9.1
ghcr.io/kube-vip/kube-vip-iptables:v0.9.1:                                        resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:cfa7a20d1e35e2b9f72051e5616854611125d75c83809bc50f7847e00c8e0bb1:    exists         |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:a7dcdcd782d9c44b9817c1d5795c704ffb7e887e6c1c6a593163613a1d175956: exists         |++++++++++++++++++++++++++++++++++++++| …
```

Bump new kube-vip version v0.9.1. v0.9.2 v1.0.0

---

tools/internal/config/accumulator.go
tools/main.go

Closes https://github.com/rancher/rancher/issues/51764.
Like the title says. Uses the dockerhub API to get the list of repositories under the `rancher` org, and then ensures that any images added relative to the merge base (default: `master`) are on this list.

Add PR check that ensures that the dockerhub repo exists for images added to `config.yaml`

---

config.yaml
regsync.yaml

Fixes# https://github.com/rancher/image-mirror/issues/1097

bump prometheus-operator to 0.79.2

---

autoupdate.yaml
config.yaml
regsync.yaml

- [?] If an entire image is being added, a repo has been created for the image in DockerHub under the `rancher` org
How can I assist with the above? Can I submit this request somewhere?
- [?] Additions, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
Adding the envoy-proxy image to image-mirror. This is necessary as I'm currently trying to use the the calico ingress gateway which uses a modified version of envoy that does not exist in the mirrored repo. Specifically the image `docker.io/rancher/mirrored-calico-envoy-proxy:v3.30.0` is expected to exist, but does not.
I've been referencing …

added quay.io/calico/envoy-proxy image v3.30.0-3

---

config.yaml
regsync.yaml

add capi version v1.10.6

---

autoupdate.yaml
config.yaml
regsync.yaml

Add calico envoy ratelimit image
Issue: https://github.com/rancher/rke2/issues/8979

Add calico envoy ratelimit image

---

config.yaml
regsync.yaml

This PR removes the `v1.12.4` tag of `coredns/coredns` because it does not exist. This tag was added in https://github.com/rancher/image-mirror/pull/1089. We have https://github.com/rancher/rancher/issues/51451 to address the addition of the `v` in the version in the autoupdate workflow.

Remove `coredns/coredns:v1.12.4`

---

config.yaml
regsync.yaml

https://github.com/longhorn/longhorn/issues/11699

feat: add Longhorn 1.9.2 images
