images-list
Bump minio version in image-list
Related Issue: rancher/rancher#27467
=> Bump minio version

images-list
**Related PR:**
Update gatekeeper chart: https://github.com/rancher/dev-charts/pull/60
Add gatekeeper crd chart: https://github.com/rancher/dev-charts/pull/61
=> Update opa-gatekeeper to v3.1.0-beta.11

images-list
https://github.com/rancherlabs/eio/issues/197
=> Added in new image to mirror

images-list
Need to add support for previous versions of istio to support upgrade testing
=> Add images to support upgrade testing

images-list
=> Add images for istio 1.7.0

images-list
Related Issue: https://github.com/rancher/rancher/issues/28441
Related PRs: https://github.com/rancher/image-mirror/pull/24, https://github.com/rancher/charts/pull/582
=> Add newline at end of images-list

images-list
Bumping Calico to v3.16.0 for https://github.com/rancher/rancher/issues/26717
Signed-off-by: Chris Kim <oats87g@gmail.com>
=> Add Calico v3.16.0 images

images-list
https://github.com/rancher/rancher/issues/26717
Signed-off-by: Chris Kim <oats87g@gmail.com>
=> Add Calico v3.16.1

images-list
Add Kiali version to 1.23.0
**Issue**
https://github.com/rancher/rancher/issues/28738
=> Add Kiali version to 1.23.0

images-list
adding initial images ( mixture of new images for 1.7.1 and existing images for 1.7.0 ) 
https://github.com/rancher/rancher/issues/28901
=> Add istio, kiali 2.5 images

images-list
=> added logging images

images-list
Remove images that should not be in mirror images list
=> Remove coredns from list

images-list
Add new image for gatekeeper v3.1.1: https://github.com/rancher/charts/pull/670
=> Add gatekeeper v3.1.1

images-list
=> add longhorn images

images-list
Add mirror debug fluentd image (v1.11.2). Add mirror debug
fluentbit image (1.5.4).
New image
[Issue: 28657](https://github.com/rancher/rancher/issues/28657)
n/a
=> Add mirror debug fluentbit image

images-list
version bump 
https://github.com/rancher/rancher/issues/29408
https://github.com/rancher/rancher/issues/29249
=> Add istio 1.7.3 and kiali 1.24.0

README.md
docs
n/a
EDIT: if you would like to check out the README rendered: https://github.com/nickgerace/image-mirror/blob/docs/README.md
=> Add images list format and multi-arch information

images-list
=> Mirror sonobuoy/sonobuoy:v0.19.0

images-list
New versions of images. Repositories are already created.
Related Issue: https://github.com/rancher/rancher/issues/29149
=> Update images for Monitoring V1 upgrade to v0.39.0

images-list
Add gatekeeper's tag v3.2.1
Related Issue: https://github.com/rancher/rancher/issues/30018
Related PR: https://github.com/rancher/charts/pull/853
=> Add gatekeeper v3.2.1

images-list
version bump
Charts PR: https://github.com/rancher/charts/pull/857
Original Issue: https://github.com/rancher/rancher/issues/29892
n/a
=> Add images for logging operator chart 3.8.0

images-list
New image / image bump
https://github.com/rancher/rancher/issues/29903
=> Add all-in-one jaeger image version 1.20

images-list
* version bump
k3s-io/k3s#2293
=> Add coredns 1.7.1 and 1.8.0

images-list
New mirrored image for rancher-externalip-webhook chart
https://github.com/rancherlabs/rancher-security/issues/499
Related to https://github.com/rancher/externalip-webhook
Related to EIO request https://github.com/rancherlabs/eio/issues/321
=> Added rancher/kube-rbac-proxy image

images-list
New image
k3s-io/k3s#2686
Repo does not currently exist
=> Add rpardini/docker-registry-proxy:0.6.1

images-list
- [ x New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
New image version for testing purposes (need it to be in the Rancher Dockerhub since that repository is whitelisted by user)
=> Add Prometheus 2.19.2

images-list
version bump
Relevant issue: https://github.com/rancher/rancher/issues/30917
n/a
=> Add images for logging 3.9.0 upstream

images-list
New image: rancher/metrics-server(multi-arch)
Version bump: calico
rancher/rancher#30134 System component image updates
=> Add calico 3.16.5

images-list
version bump
Update coredns to the latest version in k8s 1.20
=> Add coredns 1.8.1

images-list
=> Update busybox to 1.32.1

images-list
Version bump to 1.8.3
https://github.com/rancher/rancher/issues/31103
N/A
=> Add istio 1.8.3 images

images-list
New image
https://github.com/k3s-io/k3s/issues/1141
=> Add traefik 2.4.2

images-list
version bump
https://github.com/rancher/rancher/issues/31204
=> Add image for gatekeeper v3.3.0

images-list
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@suse.com>
New images: cilium v1.9.4 (latest released version)
https://github.com/rancher/rancher/issues/15087
https://github.com/rancher/rke2/issues/490
=> Add images for cilium v1.9.4 [new images]

images-list
=> Add rancher/mirrored-kube-rbac-proxy

images-list
All images are new images and new repositories. Will tie this in with a relevant EIO issue.
CPI PR: https://github.com/rancher/charts/pull/1018
CSI PR is TBD
=> Add vsphere CPI and CSI images

images-list
Version bump
https://github.com/rancher/rancher/issues/31265
https://github.com/rancher/rancher/issues/31761
=> Add istio 1.8.4 & 1.9.1

images-list
=> Add nginx 1.19.9-alpine

images-list
bump
rancher/rancher#31644
rancher/rancher#28721
https://github.com/rancher/charts/pull/1076
n/a
=> Update images for logging v2 3.9.4

images-list
New image
https://github.com/rancher/rancher/issues/29951
=> add images for rancher-alerting-driver

images-list
For https://github.com/k3s-io/k3s/issues/1141 https://github.com/k3s-io/k3s/pull/3008
=> Add Traefik v2.4.8

images-list
- [ x ] Change does not remove any existing Images or Tags in index-list.txt
- [ x ] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ x ] New entries are in format `SOURCE DESTINATION TAG`
- [ x ] New entries are added to the correct section of the list (sorted lexographically)
- [ x ] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
https://github.com/k3s-io/k3s/issues/3001
=> add entry for CoreDNS 1.8.3

images-list
Version Bump
https://github.com/rancher/rancher/issues/31979
=> Add kiali v1.32.0

images-list
=> Add etcd v3.4.15

images-list
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
Cilium update to 1.9.6
=> Add Cilium 1.9.6 images

.drone.yml
Checks that the list is sorted in CI!
N/A
for @cbron
=> Validate list sorting in CI

images-list
https://github.com/rancher/rancher/issues/31567
=> update images-list for v3.19.0 calico images

images-list
=> add etcd v3.4.16-rancher1

images-list
Version Bump
https://github.com/rancher/rancher/issues/32529
https://github.com/rancher/rancher/issues/32330
=> Add kiali v1.34.1

images-list
https://github.com/rancher/rancher/issues/31567
=> add k8s-dns images for 1.17.4

images-list
=> Update calico operator and calicoctl images

images-list
Adding a new image for Alertmanager.
Related PR: https://github.com/rancher/system-charts/pull/469
Related Issue: https://github.com/rancher/rancher/issues/31522
=> Introduce Alertmanager v0.22.0

images-list
=> Add mirrored image for gatekeeper 3.4.0

images-list
New image for `plugins/docker`
- [  ] Confirm that you can pull the new images and tags from DockerHub
=> Add plugins/docker:19.03.8

images-list
Verison bump
https://github.com/rancher/rke2/issues/1077#
=> Add updated calico images

images-list
version bump
https://github.com/rancher/rancher/issues/32748
n/a
- [] Confirm that you can pull the new images and tags from DockerHub
=> Add images for logging v2 upstream 3.9.5

images-list
Version Bump for Kiali and Istio 
https://github.com/rancher/rancher/issues/32795
https://github.com/rancher/rancher/issues/32529
https://github.com/rancher/rancher/issues/32330
N/A
=> Include kiali 1.35.0, istio 1.10.0

images-list
Related PR: https://github.com/rancher/charts/pull/1252
Related Issue: https://github.com/rancher/rancher/issues/32519
=> Add kube-state-metrics v2.0.0

images-list
version bump
https://github.com/rancher/rancher/issues/32748
n/a
=> Add logging operator for 3.10.0 logging

images-list
Version Bump
https://github.com/rancher/rancher/issues/32795
N/A
=> Include istio 1.10.1

images-list
New image tags
Related Issue: https://github.com/rancher/rancher/issues/32519
=> Add new Monitoring V2 images

images-list
New image, pause 3.5 used in k8s 1.22
https://github.com/rancher/rancher/issues/33114
=> Add pause 3.5

images-list
Related PR: https://github.com/rancher/system-charts/pull/485
=> Add Monitoring V1 bumped images

images-list
=> Add jenkins/jnlp-slave 4.7-1

images-list
Related PR: https://github.com/rancher/charts/pull/1307
Related Issue: https://github.com/rancher/rancher/issues/33210
=> Add Grafana images for 6.11.0

images-list
=> Bump nginx image

images-list
version bump
https://github.com/rancher/rancher/issues/32300
=> Add mirrored image for gatekeeper 3.5.1

images-list
https://github.com/rancher/rancher/issues/33462
- [x ] Change does not remove any existing Images or Tags in the images-list file
- [ x] Changes to scripting or CI config have been tested to the best of your ability
=> added images for rancher logging 3.12.0

images-list
- [ x] Changes to scripting or CI config have been tested to the best of your ability
=> fixed bad fluend image

images-list
version bump
For k3s-io/k3s#3565
=> Add traefik 2.4.9

images-list
- [ x] Change does not remove any existing Images or Tags in the images-list file
- [ x] Changes to scripting or CI config have been tested to the best of your ability
new image
https://github.com/rancher/security-scan/pull/48
=> added sonobouy 0.19.0 mirrored

images-list
- [x ] Change does not remove any existing Images or Tags in the images-list file
- [ -] Changes to scripting or CI config have been tested to the best of your ability
new image
https://github.com/rancher/rancher/issues/33335
=> added sonobuoy v0.52.0

images-list
=> Bump nginx image for Monitoring

images-list
New image
https://github.com/k3s-io/k3s/pull/3749
=> add new image rancher/mirrored-library-traefik

images-list
version bump 
https://github.com/k3s-io/k3s/pull/3749
=> add new tag rancher/mirrored-library-busybox:1.32.1

images-list
Version bump
https://github.com/rancher/rke2/issues/1541
=> Update the calico images

images-list
version bump
* https://github.com/k3s-io/k3s/issues/3781
=> Add traefik 2.5.0

images-list
=> add new tag rancher/mirrored-messagebird-sachet 0.2.6

images-list
https://github.com/rancher/rancher/issues/33940
https://github.com/rancher/rancher/issues/33939
https://github.com/rancher/rancher/issues/33938
https://github.com/rancher/rancher/issues/33937
https://github.com/rancher/rancher/issues/33936
https://github.com/rancher/rancher/issues/33935
https://github.com/rancher/rancher/issues/33934
https://github.com/rancher/rancher/issues/33933
=> added rancher logging 3.14.0 images

images-list
- [ x] Change does not remove any existing Images or Tags in the images-list file
- [ -] Changes to scripting or CI config have been tested to the best of your ability
=> added missing fluentbit image

images-list
Version bump sonobuoy to v0.53.2 for image-scanning
=> Add sonobuoy v0 53 2

CODEOWNERS
Adding another rancher resource to help triage PRs
=> Add Kinara as CodeOwner

images-list
New image
https://github.com/rancher/charts/pull/1474
=> add idealista/prom2teams 3.2.3

images-list
version bump
https://github.com/rancher/rancher/issues/33683
N/A
=> Add istio-1.11.2

images-list
version bump
https://github.com/rancher/rancher/issues/34017
=> Add jaegertracing-all-in-one 1.26.0

images-list
version bump
https://github.com/rancher/rancher/issues/34740
=> Add kiali v1.40.1

images-list
- [ x] Change does not remove any existing Images or Tags in the images-list file
- [x ] New entries are in format `SOURCE DESTINATION TAG`
- [x ] New entries are added to the correct section of the list (sorted lexicographically)
- [ -] Changes to scripting or CI config have been tested to the best of your ability
=> added fluent-bit 1.8.7

images-list
Version bump
https://github.com/rancher/rancher/issues/33683
=> Add istio:1.11.4 , kiali:1.41.0, jaeger-all-in-one:1.27.0

images-list
https://github.com/rancherlabs/eio/issues/630
https://github.com/rancher/rancher/issues/34577
the upstream changes the image repo from `thanosio/thanos` to  `quay.io/thanos/thanos` : https://github.com/prometheus-community/helm-charts/blame/main/charts/kube-prometheus-stack/values.yaml#L1664
=> add rancher/mirrored-thanos-thanos v0.17.2

images-list
=> Add new flannel image

images-list
=> Update flannel to v0.15.1

images-list
=> Bump addons to latest for v1.22

images-list
=> add metrics-server v0.5.1

images-list
Signed-off-by: Phan Le <phan.le@suse.com>
=> Add missing image longhornio/longhorn-share-manager v1_20211020

images-list
Version bump
https://github.com/rancher/rke2-charts/pull/203
=> Update calico images to new version

images-list
=> Add new flannel repo

README.md
=> Longhorn images are also multi-arch

images-list
version bump
* https://github.com/k3s-io/k3s/issues/4938
=> Add busybox 1.34.1 and traefik 2.5.6 

images-list
=> Update flannel-cni image

images-list
=> Calico: Update to 3.21.4

images-list
=> Update flannel to v0.16.2

images-list
=> Mirror Flannel 0.16.3 image

images-list
=> Update Calico to v3.22.0 and tigera-operator to v1.25.0

images-list
New images for logging-operator 3.17.1
https://github.com/rancher/rancher/issues/36039
=> Add logging-operator 3.17.1

images-list
=> add images for k8s 1.23

images-list
=> Update flannel image to 0.17.0

images-list
https://github.com/rancher/rke2/issues/2556
=> Update calico images

images-list
Cherry-pick commit from https://github.com/rancher/image-mirror/pull/216 to unblock testing. 
Signed-off-by: David Ko <dko@suse.com>
=> Add longhorn 1.2.4 images

images-list
=> Bump coredns to 1.9.1

images-list
Add new image for rancher-logging update
Issue: https://github.com/rancher/charts/pull/1828
=> Add rancher-logging operator image 3.17.3

images-list
Additional images for logging-operator 3.17.3
=> Additional logging-operator 3.17.3 images

images-list
- [ X ] Change does not remove any existing Images or Tags in the images-list file
- [ X ] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X ] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X ] New entries are in format `SOURCE DESTINATION TAG`
- [ X ] New entries are added to the correct section of the list (sorted lexicographically)
- [ X ] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ X ] Changes to scripting or CI config have been tested to the best of your ability
=> NeuVector mirror request for 5.0.0-b1

images-list
Version bump
https://github.com/rancher/rancher/issues/37229
N/A
=> Add OPA-Gatekeeper v3.7.1

images-list
=> Add Istio 1.11.8

images-list
=> Update Tigera operator

images-list
=> NeuVector mirror request for 5.0.0-b2

images-list
Version bump
https://github.com/rancher/rke2/issues/2859
=> Update cilium images

images-list
=> Update tigera operator to 1.23.7

images-list
- [ X ] Change does not remove any existing Images or Tags in the images-list file
- [ X ] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X ] New entries are in format `SOURCE DESTINATION TAG`
- [ X ] New entries are added to the correct section of the list (sorted lexicographically)
- [ X ] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
=> NeuVector mirror request for 5.0.0

images-list
version bump
https://github.com/rancher/rancher/issues/37219
https://github.com/rancher/rancher/issues/33739
N/A
=> Add istio 1.13.3

images-list
Update calico to 3.23.1 and operator to 1.27.1
=> Update calico to 3.23.1 and operator to 1.27.1

images-list
=> update flannel version

images-list
- https://github.com/rancher/rke/issues/2936
- https://github.com/rancher/rancher/issues/37911
=> add multiple images

CODEOWNERS
The code owners file needs to follow the pattern listed here.
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
=> Fixing the codeowners file.

images-list
version bump
https://github.com/rancher/rancher/issues/37915
https://github.com/rancher/rancher/issues/37952
N/A
=> Add istio 1.14.1

images-list
version bump
https://github.com/rancher/rancher/issues/37917
N/A
=> Add Gatekeeper 3.8.1

images-list
version bump
https://github.com/rancher/rancher/issues/37916
N/A
=> Add Sonobuoy v0.56.7

images-list
=> Updated Flannel version to v0.19.0

images-list
=> Updated cilium to version 1.12.0

images-list
=> Updated cilium-operator to 1.12.0 and startup-script

images-list
- [ X ] Change does not remove any existing Images or Tags in the images-list file
- [ X ] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X ] New entries are in format `SOURCE DESTINATION TAG`
- [ X ] New entries are added to the correct section of the list (sorted lexicographically)
- [ X ] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
=> Pump up NeuVector product version to 5.0.2

images-list
Updated Flannel image with v0.19.1
=> Updated flannel to v0.19.1

images-list
Signed-off-by: David Ko <dko@suse.com>
Add longhorn 1.3.1 release images
[](https://github.com/longhorn/longhorn/issues/4322)
N/A
=> Add 1.3.1 images

images-list
New images
https://github.com/rancher/rke2/issues/3238
=> Update cilium image

images-list
version bump
https://github.com/rancher/rancher/issues/38450
=> add gatekeeper 3.9.0

images-list
version bump
https://github.com/rancher/rancher/issues/38451
=> add istio 1.14.3

images-list
New images for logging-operator 3.17.8
=> Add images for logging-operator 3.17.8

images-list
New image tag
https://github.com/rancher/rancher/issues/38788
=> Add logging-operator 3.17.9

images-list
=> Updated flannel image

images-list
version bump
https://github.com/rancher/rancher/issues/38450
=> add curl 7.83.1 for gatekeeper

images-list
New image tag 
https://github.com/rancher/rancher/issues/38187
=> mirror gcr.io/cloud-provider-vsphere/cpi/release/manager v1.24.1

images-list
version bumps 
https://github.com/rancher/rancher/issues/38188
=> add new image tags for the rancher-vsphere-csi chart

images-list
Signed-off-by: David Ko <dko@suse.com>
https://github.com/longhorn/longhorn/issues/4449
=> Add longhorn 1.2.5 images

images-list
version bump
https://github.com/rancher/rke/issues/3034
=> add new image tags for 1.25

CODEOWNERS
=> Adds more codeowners

images-list
=> Updating rancher/mirrored-prometheus-adapter image

images-list
version bump
* https://github.com/k3s-io/k3s/issues/6222
=> Add latest traefik 2.8/2.9 images

images-list
=> adding images for grafana upgrade

images-list
Signed-off-by: Phan Le <phan.le@suse.com>
=> Add longhorn 1.3.2 images

images-list
version bump
https://github.com/rancher/rancher/issues/39343
=> Add Istio 1.15.2 images

images-list
New image
https://github.com/rancherlabs/eio/issues/1364
https://github.com/rancher/rancher/pull/39419
GH Repos:
https://hub.docker.com/r/rancher/mirrored-bci-busybox
https://hub.docker.com/r/rancher/mirrored-bci-micro
=> mirror bci images

images-list
Add version v1.2.0 of flannel-cni-plugin image
=> Add flannel-cni-plugin v1.2.0

images-list
version bump
https://github.com/rancher/rancher/issues/39397
=> Add Gatekeeper 3.10.0

.github/PULL_REQUEST_TEMPLATE.md
=> Adds question about licenses to PRs

images-list
Version bump
https://github.com/rancher/rke2/issues/3490
=> Update cilium to 1.12.3

images-list
=> Add traefik 2.9.4

images-list
Signed-off-by: Ray Chang <ray.chang@suse.com>
cc @innobead @PhanLe1010
=> docs(longhorn):  Add longhorn 1.2.6 images

images-list
version bump
https://github.com/rancher/rancher/issues/39343
=> Add Istio 1.15.3

images-list
=> Bump metrics-server to v0.6.2

images-list
Update Flannel image to v0.20.2
=> Update flannel image to v0.20.2

images-list
=> add flannel-cni-plugin v1.1.2

images-list
New calico image versions.
https://github.com/rancher/rancher/issues/39747 and https://github.com/rancher/rancher/issues/39748
=> added calico 3.22.5

images-list
https://github.com/rancher/rancher/issues/39747 and https://github.com/rancher/rancher/issues/39748
=> added calico node v3.22.5 image

images-list
https://github.com/rancher/rancher/issues/39968
=> Updated CPI image list

images-list
Added new images with updated versions for alerting drivers chart
https://github.com/rancher/rancher/issues/39784 and https://github.com/rancher/rancher/issues/39838
=> added latest images for rancher alerting chart

images-list
=> Bump up NeuVector release to 5.1.0

images-list
- EIO repo creation request: https://github.com/rancherlabs/eio/issues/1426
=> added Longhorn 1.4.0

images-list
Adds the latest tag for the sonobouy image.
=> Add new sonobouy tags

image-mirror.sh
Add support for `vnd.oci.image.index.v1`, which is needed for `quay.io/skopeo/stable:v1.10.0`. Current error:
```
Line: quay.io/skopeo/stable rancher/mirrored-skopeo-skopeo v1.10.0
quay.io/skopeo/stable rancher/mirrored-skopeo-skopeo v1.10.0
quay.io/skopeo/stable:v1.10.0 has unknown mediaType application/vnd.oci.image.index.v1+json
===
Failed copying image for rancher/mirrored-skopeo-skopeo
===
```
Also moved some logging around.
n/a
Tested here: https://hub.docker.com/r/sebtestorg2/mirrored-skopeo-skopeo/tags
=> Add support for vnd.oci.image.index.v1

images-list
- [X ] Change does not remove any existing Images or Tags in the images-list file
- [ X] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X] New entries are in format `SOURCE DESTINATION TAG`
- [ X] New entries are added to the correct section of the list (sorted lexicographically)
- [ X] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ X] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved …
=> NeuVector mirror request for 5.1.1

images-list
Update calico images to v3.25.0
=> Update Calico images to v3.25.0

.github/workflows/add-tag-to-existing-image.yml
This shows the created PR from the workflow in the workflow summary so you can directly open it from the summary view
=> Add link to created PR in workflow summary

scripts/check-new-images-exist.sh
This allows the script to be run locally (it will use branch `master`) and in Drone (it will use the before and after commit to diff for new images)
=> Use before and after commits to check img in Drone

images-list
Adds the latest tag for the sonobouy image.
=> Add sonobuoy v0.56.15

images-list
Version Bump 
https://github.com/rancher/rancher/issues/40959
=> Add Istio 1.16.3

images-list
etcd version bump to v3.5.6 image
https://github.com/rancher/rancher/issues/40993
=> bumped etcd to v3.5.6

images-list
- [ x] Change does not remove any existing Images or Tags in the images-list file
=> Bump up NeuVector relese version to 5.1.2

images-list
=> Updated images-list with Istio 1.17.2 requirements

images-list
https://github.com/rancher/rancher/issues/41207 and https://github.com/rancher/rancher/issues/41208
=> Add pause images 3.7 and 3.8

retrieve-image-tags/retrieve-image-tags.py
Output is expected to be JSON to be passed to the next workflow, current script still had my debug print line enabled
=> Remove debug print line

images-list
[Longhorn 5581](https://github.com/longhorn/longhorn/issues/5581)
version bump
https://github.com/longhorn/longhorn/issues/5581
https://github.com/longhorn/longhorn/blob/v1.3.3/deploy/longhorn-images.txt
=> docs(longhorn): Add longhorn 1.3.3 images

README.md
This adds commands to test the configuration for the workflow locally
=> Add test commands for workflow config

images-list
=> add gatekeeper 3.12

images-list
version bump: metrics-server v0.6.3
https://github.com/rancher/rancher/issues/41113
=> added metrics server image v0.6.3

images-list
Adds the latest tag for the sonobouy image.
https://github.com/rancher/cis-operator/issues/191
=> Add sonobuoy v0.56.16

images-list, retrieve-image-tags/config.json
prom2teams vresion bump
https://github.com/rancher/rancher/issues/41504
=> bump prom2teams to 4.2.1

images-list
- [ X] Change does not remove any existing Images or Tags in the images-list file
- [ X] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X] New entries are in format `SOURCE DESTINATION TAG`
- [ X] New entries are added to the correct section of the list (sorted lexicographically)
- [ X] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [ X] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved …
=> Bump up NeuVector release version to 5.1.3

images-list
=> Add ghcr.io/kube-vip/kube-vip-iptables:v0.6.0

images-list
version bump
[Longhorn 6096](https://github.com/longhorn/longhorn/issues/6096)
https://github.com/longhorn/longhorn/blob/v1.5.0/deploy/longhorn-images.txt
=> docs(longhorn): Add longhorn 1.5.0 images

images-list
…d to rancher/mirrored-cluster-api-controller:v1.4.4
New Image
https://github.com/kubernetes-sigs/cluster-api/blob/7399f5fc3021a76814d6126eff8eff49e520f61f/LICENSE
=> Add registry.k8s.io/cluster-api/cluster-api-controller:v1.4.4

images-list
version bump
[Longhorn 6274](https://github.com/longhorn/longhorn/issues/6274)
[Rancher 42041](https://github.com/rancher/rancher/issues/42041)
https://github.com/longhorn/longhorn/blob/v1.5.1/deploy/longhorn-images.txt
cc @innobead @PhanLe1010 @khushboo-rancher @roger-ryao
=> docs(longhorn): Add longhorn 1.5.1 images

images-list
version bump
[Longhorn 6102](https://github.com/longhorn/longhorn/issues/6102)
[Rancher 41622](https://github.com/rancher/rancher/issues/41622)
https://github.com/longhorn/longhorn/blob/v1.4.3/deploy/longhorn-images.txt
=> docs(longhorn): Add longhorn 1.4.3 images

images-list
Version bump
https://github.com/rancher/rancher/issues/41840
=> add rancher/mirrored-coreos-etcd v3.5.7

images-list
- [ X] Change does not remove any existing Images or Tags in the images-list file
- [ X] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [ X] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [ X] New entries are in format `SOURCE DESTINATION TAG`
- [ X] New entries are added to the correct section of the list (sorted lexicographically)
- [ X] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
=> Bump up neuvector product version to 5.2.1

images-list
=> Add Istio 1.19.0 and related images

images-list
=> Bump up neuvector product version to 5.2.2-s1

images-list
- https://hub.docker.com/r/rancher/mirrored-gmsa-webhook-k8s-gmsa-webhook
- Will be added to 2.7 in https://github.com/rancher/rancher/pull/43149
- Will be added to 2.8 on forward-port, will not be done with this PR.
New image
```bash
$ docker manifest inspect registry.k8s.io/gmsa-webhook/k8s-gmsa-webhook:v0.7.0
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 698,
"digest": "sha256:38c99a8efc9c3c4c0dca50a95f26fdcc053e84b960d114b93f9e5a426f51478d",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 698,
"digest": …
```
=> Add gmsa-webhook image for v0.7.0

.github/workflows/stale.yml
Add stale workflow similar to other `rancher` repositories
=> Add stale issue/PR workflow

images-list
longhorn/longhorn#6894
https://github.com/rancher/rancher/issues/42094
=> docs(longhorn): Add longhorn 1.4.4 images

images-list
bump etcd to v3.5.9
https://github.com/rancher/rancher/issues/43152 and https://github.com/rancher/rancher/issues/43130
=> bump etcd to v3.5.9

images-list
=> adding kiali 1.76.0

images-list
=> add mirrored-calico-operator v1.30.7

retrieve-image-tags/config.json
this PR adds etcd to scheduled PRs.
this is in continuation to the PR https://github.com/rancher/image-mirror/pull/507. 
https://github.com/rancher/rancher/issues/43152 and https://github.com/rancher/rancher/issues/43130
=> added etcd to scheduled PR config

images-list
=> Bump up NeuVector release version to 5.2.4

README.md, retrieve-image-tags/retrieve-image-tags.py
Second part of https://github.com/rancher/image-mirror/issues/500
=> Add helm-directory in retrieve-image-tags

images-list
https://github.com/rancher/rancher/issues/43726
https://github.com/rancher/rancher/issues/43600
=> adding istio 1.19.5

images-list
=> bump fluentbit

images-list
=> adding istio 1.19.6

images-list
New image
https://github.com/rancher/security-scan/pull/185
=> Add mirrored-tonistiigi-xx image

images-list
=> Bump up NeuVector release version to 5.2.4-s1

images-list
Adding NeuVector 5.3.0 release images
=> Adding NeuVector 5.3.0 release

images-list
* Add metrics-server v0.6.4
* https://github.com/rancher/rancher/issues/43109
=> [v1.28] Add metrics-server v0.6.4

images-list
* Add metrics-server v0.7.0
* https://github.com/rancher/rancher/issues/43109
=> [v1.28] Add metrics-server v0.7.0

images-list
=> adding istio 1.20.3

images-list
https://github.com/rancher/rancher/issues/44851
https://github.com/rancher/rancher/issues/44852
https://github.com/rancher/rancher/issues/44798
https://github.com/rancher/rancher/issues/44799
=> Add Cluster Proportional Autoscaler v1.8.9

images-list
Add images for new rancher-monitoring rebase.
https://github.com/rancher/rancher/issues/44614
Replaces https://github.com/rancher/image-mirror/pull/572.
=> add images for rancher-monitoring rebase

images-list
New Calico operator version needed by Calico v3.27.3
https://github.com/rancher/rke2/issues/5663
=> Added calico operator v1.32.7

images-list
=> adding istio 1.21.1 and related images

images-list
=> Adding NeuVector 5.3.2 release

images-list
=> Adding NeuVector 5.3.3 tags

images-list
=> adding images for istio 1.22

images-list
=> adding kiali 1.86

images-list
- Added images for vsphere csi 1.30 support
- https://github.com/rancher/rancher/issues/45747
=> added images for vsphere-cpi 1.30 support 

.github/workflows/ci.yml, .github/workflows/mirror-images-daily.yml, .github/workflows/mirror-images.yml, README.md, scripts/check-new-images-exist.sh
Add GitHub Action to verify prs similarly to Drone.
Updated the README.md accordingly and removed a leftover file from the Dapper Docker image.
=> Verify prs with GitHub Action

images-list
Adding NeuVector version 5.3.4
=> Add neuvector 5.3.4 version

images-list
Pre-req for https://github.com/k3s-io/k3s/issues/10718
=> Include coredns and metrics-server latest version

images-list
=> Update logging and monitoring dependencies

images-list
=> Add tags for various O&B team bumps

images-list
- version bump
- https://github.com/rancher/rancher/issues/46197
=> add support for capi v1.8.3

images-list
=> Add NeuVector version 5.4.0

images-list
=> Add NeuVector compliance config tag

images-list
version bumps
Will fix: https://github.com/rancher/rancher/issues/46567
=> Add grafana 10.4.9 and grafana-image-renderer 3.10.5

images-list
=> adding kiali, jaeger, istio images

images-list
https://github.com/longhorn/longhorn/issues/9346
https://github.com/rancher/rancher/issues/47182, https://github.com/rancher/rancher/issues/47183, https://github.com/rancher/rancher/issues/47184
=> Add longhorn-cli image

images-list
=> Add Longhorn 1.6.3 images

images-list
- [n/a] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [n/a] New entries are licensed with Rancher favored licenses - Apache 2 and MIT - or approved licenses - as according to [CNCF approved licenses](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- [n/a] New entries, when used in Rancher or Rancher's provided charts, have their corresponding origin added in Rancher's images [origins](https://github.com/rancher/rancher/blob/release/v2.7/pkg/image/origins.go) file (must be added for all Rancher versions `>= v2.7`).
- [n/a] Changes to scripting or CI config have been tested to the best of your ability
New curl image for chart usage
=> Add new curl image

images-list, images-list-daily
=> Adding NeuVector 5.4.1 tags

images-list
=> add coredns v1.11.4

images-list
=> adding istio 1.24.1

images-list
=> Add coredns 1.12.0 image

images-list
New image
https://github.com/rancher/rancher/issues/47428
The new tag will be used in cluster template in KDM
=> mirror rancher/nginx-ingress-controller-defaultbackend 1.5-rancher2

retrieve-image-tags/config.json
=> add config for tonistiigi-xx

images-list
=> Add image used by monitoring 66.7

images-list
Follow up to: https://github.com/rancher/image-mirror/pull/823 (I missed fixing patches and they accidentally downgraded some tags so didn't notice this image)
=> Add new prom operator

images-list
New Images
https://github.com/rancher/ob-team-charts/pull/9#issuecomment-2635428107
=> new Prom Config reloader and thanos

images-list
- Add cluster-api-controller:v1.9.4
- https://github.com/rancher/rancher/issues/47934
=> [v1.32] Add `cluster-api-controller` `v1.9.4`

images-list
- Add cluster-api-controller:v1.9.5
-  https://github.com/rancher/rancher/issues/47934
=> [v1.32] Add cluster-api-controller v1.9.5

images-list
=> Adding new tag(s) for Longhorn v1.7.3 image(s)

images-list
=> Adding new tag(s) for Longhorn v1.8.1 image(s)

images-list
=> Add images needed for monitoring rebase to 69.8

images-list
=> Add coredns `1.12.1` image

images-list
=> Add new curl image tags

.github/workflows/pull-request.yml
Partially solves https://github.com/rancher/rancher/issues/49872.
=> Add checks for `config.yaml` formatting and `regsync.yaml` being in sync with `config.yaml`

images-list
=> Add cloud-provider-vsphere v1.33

regsync.yaml, tools/internal/regsync/config.go, tools/main.go
This is for https://github.com/rancher/rancher/issues/50180.
=> Set the user agent of regsync to `rancher-image-mirror`

retrieve-image-tags/config.json
Auto sync config update
https://github.com/rancher/rancher/issues/50381
=> Use github-latest-release for tonistiigi/xx

images-list
=> Adding new tag(s) for Longhorn v1.8.2 image(s)

config.yaml, regsync.yaml, tools/internal/config/config.go, tools/internal/regsync/config.go
Fixes https://github.com/rancher/rancher/issues/50651.
=> Add `repoAuth: true` to prime registry

README.md
Part of https://github.com/rancher/rancher/issues/49871.
=> Add documentation for autoupdate.yaml

.github/workflows/pull-request.yml, tools/internal/config/accumulator.go, tools/main.go
Closes https://github.com/rancher/rancher/issues/50477.
=> Add validation that checks for `SourceImage`-`TargetImageName` duplication in `config.yaml`.

config.yaml, regsync.yaml
New image for Rancher Supportability Review.
=> Mirror library/redis:7.2.9

README.md, tools/internal/autoupdate/config.go, tools/internal/autoupdate/config_test.go
Closes https://github.com/rancher/rancher/issues/50421.
=> Allow pull request reviewers to be configured for each entry in `autoupdate.yaml`

tools/internal/autoupdate/config.go, tools/internal/autoupdate/config_test.go
Closes https://github.com/rancher/rancher/issues/50985.
=> Require at least one reviewer for each `autoupdate.yaml` entry

config.yaml, regsync.yaml
Adding windows-exporter `0.31.2`
=> Mirror windows exporter 0.31.2
